# v3 syntax
version: "3"

# Named volumes
volumes:
  # MySQL Data
  newsl6-mysql-data:
    driver: local

services:
  # MySQL (5.7)
  db:
    image: mysql:5.7
    container_name: newsl6-mysql
    volumes:
      - newsl6-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=newsl6
      - MYSQL_USER=newsl6
      - MYSQL_PASSWORD=newsl6
      - MYSQL_ROOT_PASSWORD=newsl6
  # PHP (with Nginx)
  app:
    image: ambientum/php:7.3-nginx
    container_name: newsl6-app
    depends_on:
      - db
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - db
  # PHPMYADMIN
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: newsl6-phpmyadmin
    depends_on:
      - db
    links:
      - db
    ports:
      - "81:80"
    environment:
      - PMA_HOST=db
      - MYSQL_USER=newsl6
      - MYSQL_PASSWORD=newsl6
      - MYSQL_ROOT_PASSWORD=newsl6
